release:

builds:
- id: aws-ssm-document
  main: main.go
  binary: aws-ssm-document
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
  env:
  - CGO_ENABLED=0

archives:
- builds:
  - aws-ssm-document
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^examples:'

nfpms:
  - license: MIT
    maintainer: Fabio Gollinucci
    description: AWS SSM Document CLI
    homepage: https://github.com/daaru00/aws-ssm-document-cli
    suggests:
      - nodejs
      - python
    formats:
      - rpm
      - deb
